### PR TITLE
Dependency Updates and Clean Up

### LINKED ISSUE #8: Update Gatsby and all dependencies
# What

The version of Gatsby and many of the plugins and other dependencies we are using for the website are quite out of date. Running `npm outdated` gives the following:

```txt
Package                         Current  Wanted  Latest  Location                                     Depended by
contentful-import                7.9.42  7.9.42  8.5.21  node_modules/contentful-import               verdancesite
gatsby                            4.0.2  4.25.3   5.4.2  node_modules/gatsby                          verdancesite
gatsby-plugin-google-analytics    4.0.0  4.25.0   5.4.0  node_modules/gatsby-plugin-google-analytics  verdancesite
gatsby-plugin-image               2.1.0  2.25.0   3.4.0  node_modules/gatsby-plugin-image             verdancesite
gatsby-plugin-manifest            4.0.0  4.25.0   5.4.0  node_modules/gatsby-plugin-manifest          verdancesite
gatsby-plugin-react-helmet        5.0.0  5.25.0   6.4.0  node_modules/gatsby-plugin-react-helmet      verdancesite
gatsby-plugin-sass                5.0.0  5.25.0   6.4.0  node_modules/gatsby-plugin-sass              verdancesite
gatsby-plugin-sharp               4.1.0  4.25.0   5.4.0  node_modules/gatsby-plugin-sharp             verdancesite
gatsby-plugin-sitemap             5.0.0  5.25.0   6.4.0  node_modules/gatsby-plugin-sitemap           verdancesite
gatsby-source-contentful          6.0.0   6.1.4   8.4.1  node_modules/gatsby-source-contentful        verdancesite
gatsby-source-filesystem          4.1.0  4.25.0   5.4.0  node_modules/gatsby-source-filesystem        verdancesite
gatsby-transformer-sharp          4.1.0  4.25.0   5.4.0  node_modules/gatsby-transformer-sharp        verdancesite
marked-react                      1.3.0   1.3.2   1.3.2  node_modules/marked-react                    verdancesite
netlify-cli                      2.71.0  2.71.0  12.7.2  node_modules/netlify-cli                     verdancesite
react                            17.0.2  17.0.2  18.2.0  node_modules/react                           verdancesite
react-dom                        17.0.2  17.0.2  18.2.0  node_modules/react-dom                       verdancesite
sass                             1.43.4  1.57.1  1.57.1  node_modules/sass                            verdancesite
swiper                            8.1.4   8.4.6   8.4.6  node_modules/swiper                          verdancesite
```

As you can see, we are a not only a major version of gatsby behind but 25 minor versions behind in v4. As well as a major version back in react from v17 to v18. 

## Why

I believe it is necessary to update everything as much as we can, ideally completely caught up with the latest versions of everything.

Here are some reasons we should update

* Gatsby is dropping support for node 14 and 16 in favor of latest LTS in Node@18 [(Reference)](https://www.gatsbyjs.com/docs/reference/release-notes/migrating-from-v4-to-v5/#minimal-nodejs-version-1800)
* Gatsby 5 supports React version 18 [(Reference)](https://www.gatsbyjs.com/docs/reference/release-notes/migrating-from-v4-to-v5/#minimal-required-react-version-is-18)
* Updates to GraphQL 16 [(Reference)](https://www.gatsbyjs.com/docs/reference/release-notes/migrating-from-v4-to-v5/#update-to-graphql-16)
* Many other Gatsby plugins have updated to use the newest versions of Gatsby.

## Plan

I have tried a quick `npm update` calls for different dependencies and it kind of went haywire, but they were ad hoc for the purposes of testing the waters. 

### Careful

We could follow the [v4 to v5 Migration Guide](https://www.gatsbyjs.com/docs/reference/release-notes/migrating-from-v4-to-v5/) and carefully update each dependency on its own by tracking fixes, improvements, and breaking changes to support the latest version of Gatsby 4 and then do a full upgrade to 5. 

This approach _could_ be the easiest or could be the hardest. It really depends on finding the right order to update each package in and how much of an impact that has on the current code. If its smooth, its smooth, but one or two issues or breaking changes could prove to be a real pain.

### Clean Slate

We could simply start a new branch, wipe everything away and initialize a new Gatsby project with the newest versions of everything we need. Given the current scope of the website, this honestly wouldn't be too big of an undertaking and would set us up for success when adding new pages, updating content, and general upkeep in the future. 

This could also give us the opportunity to clean up a few things in the codebase and implement some of the other ideas we have had.

### Something New

Over the past couple years, the Static Site Generator (SSG) and Server Side Rendered (SSR) landscape has change quite a bit, with exciting technology being built around [Next.js/Vercel](https://nextjs.org/), [Remix.js](https://remix.run/), and [Atro](https://astro.build/), we have many options for how we build and manage our website. Below you will find my opinions and options on what we could migrate to:

#### [Next.js](https://nextjs.org/)

Next would be the most natural migration from Gatsby. I see Next as the spiritual successor to Gatsby, and, in my opinion, the torch has been passed from Gatsby to Next.js. The Next and Vercel ecosystem are thriving and growing. Next.js is primarily built on top of React and other popular web technologies and includes SSR capabilities and other integrations.

Contentful has [documentation](https://www.contentful.com/nextjs-starter-guide/) about how to integrate with Next.js and I believe it would be somewhat similar to how Gatsby integrates with Contentful.

#### [Astro](https://astro.build/)

Astro seems to be a really cool up-and-coming SSG/SSR framework for building websites. I was testing out Astro recently and really like how its put together. One of the coolest features they have is native Markdown support where building out a page or piece of content can be done completely in Markdown, providing an easy, semi-nontechnical way to update and add new content to the site. 

Astro supports many CMS systems including [Contentful](https://docs.astro.build/en/guides/cms/contentful/)

Astro is also announcing their v2.0 next week so this could be an exciting time to jump on board. 

#### [Remix.js](https://remix.run/)

This is the framework I am the least familiar with. I don't believe it supports SSG, but it is quite fully featured otherwise. Remix is built and maintained by some of the most prolific open source developers in the React and front-end space and has gained a large following in its time.

### PR DESCRIPTION
**Pull request by colevoss**
# What

Updates all dependencies by doing a clean Gatsby init and porting the website to the newly generated Gatsby project

closes #8 

## Todo

- [ ] Set up Netlify
  - [ ] Set `NODE_VERSION` to `18` right before merging this PR [See Here](https://docs.netlify.com/configure-builds/manage-dependencies/#node-js-and-javascript)
- [x] Port 404 Page
- [x] Npm Audit
- [x] Screenshots in PR
- [x] Contentful API Environment Variables

## Screenshotts

Below you will find screen shots of the site at different sizes. 

_note: for some reason the screenshots from Chrome's dev tools removed some of the right margin so I included a reference shot to show that it is properly padded_

<details>
  <summary>Reference</summary>
BetterReference
</details>

<details>
  <summary>4k</summary>
4k
</details>

<details>
  <summary>Desktop</summary>
  Desktop
</details>

<details>
  <summary>Laptop</summary>
Laptop
</details>

<details>
  <summary>Tablet</summary>
Tablet
</details>

<details>
  <summary>Mobile</summary>
Tablet
</details>

### CODE REVIEW

**Comment by etanb** [comment]
@colevoss tag me when this PR is ready!

**Comment by etanb** [comment]
Once I added the `.nvmrc` file, seems to work fine and we should have one for local development anyways. @colevoss , thanks so much for this PR! Looks great.

**Review by etanb — APPROVED** [review]
Any idea how we convey / set these for new developers working on the project? The build will fail (obviously) if you build locally and `CONTENTFUL_ACCESS_TOKEN` and `CONTENTFUL_SPACE_ID` aren't set. My temporary solution was copy/pasting them into our shared Engineering folder in 1password. What do you think @colevoss re: best practices for developing locally with envars?

**Comment by colevoss** [comment]
> Any idea how we convey / set these for new developers working on the project? The build will fail (obviously) if you build locally and `CONTENTFUL_ACCESS_TOKEN` and `CONTENTFUL_SPACE_ID` aren't set. My temporary solution was copy/pasting them into our shared Engineering folder in 1password. What do you think @colevoss re: best practices for developing locally with envars?

I have added the contentful credentials to our 1Password but I'm not sure if everyone can see that in our vault. I think the example file and 1Password is a good idea.

**Pull request merged**
